#! /bin/bash
#
# banshee       This script starts and stops the bansshee anti-SSH-dictionary-attack daemon
#
# chkconfig:    - 50 50
# description:  bansshee monitors log files to detect SSH dictionary attacks and uses the iptables firewall to block attackers.

# Source function library.
. /etc/init.d/functions

RETVAL=0

start()
{
  echo -n $"Starting banshee: "
  daemon /usr/local/sbin/bansshee
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && /bin/touch /var/lock/subsys/bansshee
  return $RETVAL
}

stop()
{
  echo -n $"Stopping banshee: "
  killproc bansshee
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && /bin/rm -f /var/lock/subsys/bansshee
  return $RETVAL
}

restart()
{
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reload)
    restart
    ;;
  status)
    status bansshee
    ;;
  condrestart)
    [ -f /var/lock/subsys/bansshee ] && restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
    exit 1
esac

exit $?

